import {StyleSheet, Dimensions} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1A1A',
  },
  header: {
    position: 'absolute',
    height: 173,
    left: 0,
    right: 0,
    top: 0,
    backgroundColor: '#0D0D0D',
  },
  logo: {
    position: 'absolute',
    width: 110.34,
    height: 32,
    left: (Dimensions.get('window').width - 110.34) / 2,
    top: 70,
  },
  form: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    gap: 4,
    position: 'absolute',
    height: 54,
    left: 24,
    right: 24,
    top: 142,
  },
  button: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 18,
    gap: 8,
    width: 52,
    height: 52,
    backgroundColor: '#1E6F9F',
    borderRadius: 6,
    flex: 0,
  },
  input: {
    alignItems: 'center',
    padding: 16,
    gap: 8,
    color: '#FFF',
    width: 271,
    height: 54,
    backgroundColor: '#262626',
    borderRadius: 9,
    flex: 1,
  },
  containerTasks: {
    flexDirection: 'column',
    flex: 1,
    alignItems: 'flex-start',
    padding: 0,
    marginVertical: 20,
    height: 247,
    left: 24,
    right: 24,
    top: 228,
  },
  containerTasksDivision: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    padding: 0,
    marginHorizontal: 10,
    marginVertical: 20,
    width: 327,
    height: 19,
    flex: 0,
    alignSelf: 'stretch',
  },
  containerTaskCreated: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    marginHorizontal: 4,
    width: 87,
    height: 19,
    flex: 1,
    alignSelf: 'flex-end',
  },
  containerTasksDone: {
    flexDirection: 'row',
    flex: 1,
    padding: 0,
    marginHorizontal: 4,
    width: 111,
    height: 19,
    alignSelf: 'flex-end',
  },
  taskCreatedDoneText: {
    flexDirection: 'row',
    fontWeight: '900',
    alignItems: 'center',
    padding: 0,
    color: '#4EA8DE',
    marginBottom: 8,
    width: 87,
    height: 19,
    flex: 0,
  },
  taskCreatedDoneNumberText: {
    color: '#D9D9D9',
    fontWeight: '900',
  },
  containerNumberText: {
    marginBottom: 12,
    justifyContent: 'center',
    borderRadius: 999,
    color: '#D9D9D9',
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 2,
    paddingHorizontal: 8,
    gap: 10,
    width: 25,
    height: 19,
    backgroundColor: '#333333',
    flex: 0,
    alignSelf: 'auto',
    textAlign: 'center',
  },
  containerTaskIsEmpty: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: 20,
    marginVertical: 16,
    width: 327,
    height: 208,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  textOneEmpty: {
    marginTop: 16,
    color: '#808080',
    fontWeight: '800',
  },
  textTwoEmpty: {
    color: '#808080',
  },
});
